version: "3"

services:
  app:
    build:
      context: .
    container_name: library-app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

  db:
    image: 'postgres:13.1-alpine'
    container_name: library-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      -


  mongodb:
    image: mongo
    container_name: library-mongodb
    ports:
      - 27017:27017